<$PLAN9/src/mkhdr

CFLAGS="-I. -O0 -Wno-char-subscripts -Wno-array-bounds -Wno-deprecated-declarations"

TARG=5l
OFILES=\
	asm.$O\
	list.$O\
	noop.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	enam.$O\
	compat.$O\

HFILES=\
	l.h\
	../5c/5.out.h\

<$PLAN9/src/mkone

BIN=../bin

../5c/enam.c: ../5c/5.out.h
	@ { cd ../5c; mk enam.c }

enam.$O:	../5c/enam.c
	$CC $CFLAGS ../5c/enam.c

x:V:	$O.out
	$O.out -la -o/dev/null x.5
