<$PLAN9/src/mkhdr

CFLAGS="-I. -O0 -Wno-char-subscripts -Wno-array-bounds -Wno-deprecated-declarations"

TARG=5a
OFILES=\
	y.tab.$O\
	lex.$O\

HFILES=\
	../5c/5.out.h\
	y.tab.h\
	a.h\

YFILES=a.y\

<$PLAN9/src/mkone
YFLAGS=-D1 -d
BIN=../bin

lex.$O:	../cc/macbody ../cc/lexbody
