<$PLAN9/src/mkhdr

CFLAGS="-I. -O0 -Wno-char-subscripts -Wno-array-bounds -Wno-deprecated-declarations"

TARG=8l
OFILES=\
	asm.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	list.$O\
	enam.$O\
	compat.$O\

HFILES=\
	l.h\
	../8c/8.out.h\

BIN=/$objtype/bin
CFILES=${OFILES:%.$O=%.c}
CFILES=${CFILES:enam.c=../8c/enam.c}
UPDATE=\
	mkfile\
	$HFILES\
	$CFILES\
	${TARG:%=/386/bin/%}\

<$PLAN9/src/mkone

BIN=../bin
enam.$O:	../8c/enam.c
	$CC $CFLAGS ../8c/enam.c

