<$PLAN9/src/mkhdr

CFLAGS="-O0 -Wno-char-subscripts -Wno-array-bounds -Wno-deprecated-declarations"

LIB=cc.a$O
OFILES=\
	y.tab.$O\
	lex.$O\
	mac.$O\
	dcl.$O\
	acid.$O\
	pickle.$O\
	bits.$O\
	com.$O\
	scon.$O\
	funct.$O\
	sub.$O\
	com64.$O\
	compat.$O\
	dpchk.$O\
	omachcap.$O\

HFILES=cc.h\
	y.tab.h\

YFILES=cc.y\

CURCC=6c 8c qc vc
OTHERCC=1c 2c 5c 7c kc

LIBOBJ=${OFILES:%=$LIB(%)}

<$PLAN9/src/mklib

install:V:	$LIB
	date

$LIB:	$LIBOBJ
	$AR rsc $LIB $OFILES

# There seems to be a bug in plan9port's mk.
# The following recipe thinks that mac.$O depends
# on macbody.$O instead of just macbody. If you
# update macbody, make sure you mk clean first
#mac.$O:	macbody

everything:V:
	# mk the current compilers
	for(DIR in cc $CURCC){
		cd ../$DIR
		mk nuke
		mk install
	}
	# mk all the others with those
	for(DIR in cc $CURCC $OTHERCC){
		cd ../$DIR
		mk nuke
		mk installall
		mk clean
	}
