<$PLAN9/src/mkhdr

CFLAGS="-I. -O0 -Wno-char-subscripts -Wno-array-bounds -Wno-deprecated-declarations"

TARG=8a
OFILES=\
	y.tab.$O\
	lex.$O\

HFILES=\
	../8c/8.out.h\
	y.tab.h\
	a.h\

YFILES=a.y\

UPDATE=\
	mkfile\
	a.y\
	lex.c\
	a.h\
	${TARG:%=/386/bin/%}\

<$PLAN9/src/mkone
YFLAGS=-D1 -d
BIN=../bin

lex.$O:	../cc/macbody ../cc/lexbody ../cc/compat
