<$PLAN9/src/mkhdr

CFLAGS="-I. -O0 -Wno-char-subscripts -Wno-array-bounds -Wno-deprecated-declarations"

TARG=8c
OFILES=\
	cgen.$O\
	cgen64.$O\
	div.$O\
	enam.$O\
	list.$O\
	machcap.$O\
	mul.$O\
	peep.$O\
	pgen.$O\
	pswt.$O\
	reg.$O\
	sgen.$O\
	swt.$O\
	txt.$O\

HFILES=\
	gc.h\
	8.out.h\
	../cc/cc.h\

LIB=../cc/cc.a$O

<$PLAN9/src/mkone

BIN=../bin
$LIB:
	cd ../cc
	mk install
	#mk clean


%.$O: ../cc/%.c
	$CC $CFLAGS ../cc/$stem.c


enam.c:	8.out.h
	rc ./mkenam
